"""Reaction-diffusion solver for a simple acid-quencher resist model.

System:

    dA/dt = D_A * laplacian(A) - k * A * Q
    dQ/dt =                    - k * A * Q

``A`` is the acid concentration (initially generated by exposure) and
``Q`` is a quencher that consumes acid on contact. The reaction term
``k * A * Q`` is purely local; only ``A`` diffuses.

Time integration is explicit Euler with a step that satisfies both the
diffusion CFL bound ``dx**2 / (4 D_A)`` and a coarse reaction stability
estimate ``1 / (k * max(A0, Q0, 1))``. The coupled fields are advanced
with a Strang-friendly arrangement (one Laplacian + one reaction update
per step), which is sufficient for the study-grade comparisons this lab
needs.
"""

from __future__ import annotations

import math

import torch

from src.resist.diffusion_fd import laplacian_5pt


def step_reaction_diffusion(
    A: torch.Tensor,
    Q: torch.Tensor,
    D_A: float,
    k: float,
    dt: float,
    dx: float,
) -> tuple[torch.Tensor, torch.Tensor]:
    """One explicit Euler step of the coupled system."""
    lap_A = laplacian_5pt(A, dx)
    AQ = A * Q
    A_new = A + dt * (D_A * lap_A - k * AQ)
    Q_new = Q - dt * k * AQ
    # Clamp to non-negative — explicit Euler can dip below zero near
    # high-gradient boundaries when dt approaches the stability limit.
    A_new = A_new.clamp(min=0.0)
    Q_new = Q_new.clamp(min=0.0)
    return A_new, Q_new


def evolve_reaction_diffusion(
    A0: torch.Tensor,
    Q0: torch.Tensor,
    D_A: float,
    k: float,
    t_end: float,
    dx: float,
    n_steps: int | None = None,
    cfl_safety: float = 0.5,
) -> tuple[torch.Tensor, torch.Tensor]:
    """Evolve ``(A, Q)`` over ``[0, t_end]``.

    With ``n_steps=None`` the step is chosen automatically from the
    smaller of the diffusion and reaction time-scales.
    """
    if D_A < 0 or k < 0 or t_end < 0:
        raise ValueError("D_A, k, t_end must all be non-negative")
    if t_end == 0:
        return A0.clone(), Q0.clone()

    if n_steps is None:
        dt_diff = (dx * dx) / (4.0 * D_A) if D_A > 0 else float("inf")
        max_AQ = float(max(A0.abs().max().item(), Q0.abs().max().item(), 1e-6))
        dt_react = 1.0 / (k * max_AQ) if k > 0 else float("inf")
        dt_max = cfl_safety * min(dt_diff, dt_react)
        n_steps = max(1, int(math.ceil(t_end / dt_max)))

    dt = t_end / n_steps
    A, Q = A0, Q0
    for _ in range(n_steps):
        A, Q = step_reaction_diffusion(A, Q, D_A, k, dt, dx)
    return A, Q
